# Copyright (C) 2023 akquinet GmbH

# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


# this config is a copy from the EU homeserver.yaml, changed values are marked with # changed

#####################################################################################################
# Modules                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#modules #
#####################################################################################################
####################################################################################################
# Server                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#server #
####################################################################################################
server_name: "synapse" # changed, change this to your local ip address in order to access the homeserver from smartphone in your network
pid_file: "/data/homeserver.pid" # changed
# Default: serve_server_wellknown: false
serve_server_wellknown: true
soft_file_limit: 0
presence:
  enabled: true
require_auth_for_profile_requests: false
limit_profile_requests_to_users_who_share_rooms: false
include_profile_data_on_invite: true
allow_public_rooms_without_auth: false
allow_public_rooms_over_federation: false
default_room_version: "9"
gc_min_interval: [1s, 10s, 30s]
filter_timeline_limit: 100
block_non_admin_invites: false
enable_search: true
listeners: # changed
  - port: 8083
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [ client, federation ]
        compress: false
dummy_events_threshold: 10
delete_stale_devices_after: 1y
#################################################################################################################
# HomeServer blocking                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#homeserver-blocking #
#################################################################################################################
hs_disabled: false
hs_disabled_message: "Reason for why the HS is blocked"
limit_usage_by_mau: false
max_mau_value: 0
mau_trial_days: 0
mau_limit_alerting: true
mau_stats_only: false
require_membership_for_aliases: true
allow_per_room_profiles: true
redaction_retention_period: 7d
user_ips_max_age: 28d
request_token_inhibit_3pid_errors: false
#################################################################################################
# TLS                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#tls #
#################################################################################################
federation_verify_certificates: true
federation_client_minimum_tls_version: 1
########################################################################################################
# Federation                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#federation #
########################################################################################################
allow_profile_lookup_over_federation: true
allow_device_name_lookup_over_federation: false
#####################################################################################################
# Caching                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#caching #
#####################################################################################################
event_cache_size: 10K
######################################################################################################
# Database                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#database #
######################################################################################################
database: # changed
  name: psycopg2
  args:
    user: synapse
    password: synapsepassword
    database: synapse
    host: synapse-db
    port: 5432
    sslmode: "prefer"
    cp_min: 5
    cp_max: 10
#####################################################################################################
# Logging                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#logging #
#####################################################################################################
log_config: "/data/docker.log.config" # changed
##########################################################################################################
# Ratelimiting                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#ratelimiting #
##########################################################################################################
rc_message:
  per_second: 0.2
  burst_count: 10
rc_registration:
  per_second: 0.17
  burst_count: 3
rc_registration_token_validity:
  per_second: 0.1
  burst_count: 5
rc_login:
  address:
    per_second: 600
    burst_count: 600
  account:
    per_second: 600
    burst_count: 600
  failed_attempts:
    per_second: 600
    burst_count: 600
rc_admin_redaction:
  per_second: 0.2
  burst_count: 10
rc_joins:
  local:
    per_second: 0.1
    burst_count: 10
  remote:
    per_second: 0.03
    burst_count: 12
rc_joins_per_room:
  per_second: 1
  burst_count: 10
rc_3pid_validation:
  per_second: 0.003
  burst_count: 5
rc_invites:
  per_room:
    per_second: 0.3
    burst_count: 10
  per_user:
    per_second: 0.003
    burst_count: 5
  per_issuer:
    per_second: 0.3
    burst_count: 10
rc_third_party_invite:
  per_second: 0.2
  burst_count: 10
rc_federation:
  window_size: 1000
  sleep_limit: 10
  sleep_delay: 500
  reject_limit: 50
  concurrent: 3
federation_rr_transactions_per_room_per_second: 50
#########################################################################################################
# Media Store                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#media-store #
#########################################################################################################
enable_media_repo: true
media_store_path: "/data/media_store" # changed
max_upload_size: 120M
max_image_pixels: 32M
dynamic_thumbnails: false
media_retention:
  local_media_lifetime: 90d
  remote_media_lifetime: 14d
url_preview_enabled: false
max_spider_size: 10M
oembed:
  disable_default_providers: false
#####################################################################################################
# Captcha                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#captcha #
#####################################################################################################
##################################################################################################
# TURN                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#turn #
##################################################################################################
##########################################################################################################
# Registration                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#registration #
##########################################################################################################
enable_registration: false
enable_registration_without_verification: false
# registrations_require_3pid
# disable_msisdn_registration: false
enable_3pid_lookup: true
registration_requires_token: false
registration_shared_secret: "some-secret" # changed
# registration_shared_secret_path: "/secret/registration_shared_secret" # changed
bcrypt_rounds: 14
allow_guest_access: false
# enable_set_displayname defaults to true
enable_set_displayname: false
enable_set_avatar_url: true
enable_3pid_changes: true
autocreate_auto_join_rooms: true
autocreate_auto_join_rooms_federated: true
autocreate_auto_join_room_preset: public_chat
auto_join_mxid_localpart: system
auto_join_rooms_for_guests: true
inhibit_user_in_use_error: false
#####################################################################################################################
# User session management                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#user-session-management #
#####################################################################################################################
refreshable_access_token_lifetime: 5m
#####################################################################################################
# Metrics                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#metrics #
#####################################################################################################
enable_metrics: true
enable_legacy_metrics: false
report_stats: true # changed
report_stats_endpoint: http://host.docker.internal:9020/add-statistics-data # changed
###############################################################################################################
# API Configuration                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#api-configuration #
###############################################################################################################
track_puppeted_user_ips: false
track_appservice_user_ips: false
macaroon_secret_key: "some-secret" # changed
form_secret: "some-secret" # changed
##########################################################################################################
# Signing Keys                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#signing-keys #
##########################################################################################################
signing_key_path: "/data/docker.signing.key" # changed
key_refresh_interval: 1d
suppress_key_server_warning: false
########################################################################################################################
# Single sign-on integration                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#single-sign-on-integration #
########################################################################################################################
##################################################################################################
# Push                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#push #
##################################################################################################
push:
  include_content: true
  group_unread_count_by_room: true
###################################################################################################
# Rooms                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#rooms #
###################################################################################################
# encryption_enabled_by_default_for_room_type defaults to "off".
encryption_enabled_by_default_for_room_type: all
user_directory:
  enabled: true
  # search_all_users defaults to False
  search_all_users: true
  # prefer_local_users defaults to false
  prefer_local_users: true
stats:
  enabled: true
server_notices:
  system_mxid_localpart: notices
  system_mxid_display_name: "Server Notices"
  system_mxid_avatar_url: ""
  room_name: "Server Notices"
enable_room_list_search: true
#########################################################################################################
# Opentracing                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#opentracing #
#########################################################################################################
#####################################################################################################
# Workers                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#workers #
#####################################################################################################
send_federation: true
##################################################################################################################
# Coordinating workers                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#coordinating-workers #
##################################################################################################################
redis: # changed
################################################################################################################
# Background Updates                                                                                           #
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#background-updates #
################################################################################################################
background_updates:
  background_update_duration_ms: 100
  sleep_enabled: true
  sleep_duration_ms: 1000
  min_batch_size: 1
  default_batch_size: 100
